### ISSUE TITLE
Release tags explanation needed (`x.y` vs `yyyy.mm`)

### ISSUE THREAD

**Issue by Levivb** [pi-hole/docker-pi-hole#1053]
Hey,

This is not really a bug report, but more of a question regarding the tags created in this repository.
Last year I installed docker Pihole version 5.8 thinking the releases following SemVer would make the most sense.
5.8 was released in april 2021 and pretty much every few months prior to that a new (minor) release was tagged in SemVer format (see https://github.com/pi-hole/docker-pi-hole/tags?after=2021.11).
Nowadays I only see releases tagged in the format `<year>.<month>`.  Is this the new format that should be followed when updating Pihole in docker or is SemVer still to being followed? If `<year>.<month>` should be followed, is each tag a stable version? (apart of the [2022.04.2beta](https://github.com/pi-hole/docker-pi-hole/releases/tag/2022.04.2beta) tag created yesterday I don't see any alpha/beta/rc releases :)

Looking for a bit of clarification here :)

Regards,
Levi

**Comment by PromoFaux** [comment]
See the release notes here for 2021.09: https://github.com/pi-hole/docker-pi-hole/releases/tag/2021.09

We moved away from semver for the docker container because there isn't really a meaningful way to make it work. The internal Pi-hole components do follow semver. Generally a docker image is only cut when there are updates for the internal Pi-hole components, however the last couple have been due to changes in Docker 20.10.14 - with no actual functional Pi-hole changes. Normally releases would be much more stable

**Comment by Levivb** [comment]
Alright thanks for clarifying :)

I tried to find a post about it somewhere, but missed the release notes of 2021.09. Thanks for the link!
So now I have a year of updates and changes to activate 😅  (keeping the 'sometimes things do go wrong' in mind)

Closing this as the question is answered 👍
