### ISSUE TITLE
Latest version point to 5.15.4 version instead of 5.15.5

### ISSUE THREAD

**Issue by mariushosting** [pi-hole/docker-pi-hole#1318]

**Comment by PromoFaux** [comment]
@mariushosting - Just looking over your blog announcements - you should probably tie it to the [releases  on the docker repo](https://github.com/pi-hole/docker-pi-hole/releases) and not just go off of the core version - which as you have noticed is not always reflected in the `pihole/pihole` image.

**Comment by mariushosting** [comment]
> @mariushosting - Just looking over your blog - you should probably tie it to the [releases on the docker repo](https://github.com/pi-hole/docker-pi-hole/releases) and not just go off of the core version - which as you have noticed is not always reflected in the `pihole/pihole` image.

Thank you! I have updated my post. However this is something that creates confusion for users when they see different versions, one for the core and the other for Docker.

**Comment by PromoFaux** [comment]
Not that I want to tell you how to run your blog, but you don't need to mention the core release version at all. It's all contained within the docker tag notes

![image](https://user-images.githubusercontent.com/1998970/218322286-7e1ea7be-0071-4da1-9def-a661e9c2b7e5.png)

**Comment by mariushosting** [comment]
The fact remains that when people look at Pi-Hole version on the frontend, they will get confused 
![218300873-751610f7-06ce-4836-b986-8c8c0dc7063b](https://user-images.githubusercontent.com/37554361/218323746-7fada198-d43b-4627-bcc1-0c37ffa9743d.png)

**Comment by PromoFaux** [comment]
>they will get confused because they always check the CORE version.

There are three different version numbers at play for the core product. The Pi-hole repo, FTL, and the Web interface. 

The docker container is separate to those version numbers and if users are running the _docker_ container then the only version number to pay attention to is the _docker_ container version. If the docker container does not contain the latest version of a particular component it is because the container has not been updated to include this version. This could either be because it is not immediately needed (in this case, the patch has no affect on the docker container) or we just haven't gotten around to tagging a new docker container image yet.

For the purposes of your blog (and anyone using the docker container) the only version you need to pay attention to is the docker tag here: https://github.com/pi-hole/docker-pi-hole/releases

In your screenshot it shows that the Docker Tag is `2023.02.0` - and if you look at the release notes for `2023.02.0`, you will see that `v5.15.4` is expected for the Pi-hole core version.

Anyway, enough of this pointless back and forth - I've tagged a new container that includes the the 5.15.5 patch that has absolutely no affect on the docker container other than to show a different version number for one of the components in the footer than it did previously.

Again. Docker Tag is the version you should be focussing on.
