### ISSUE TITLE
Landing page shows default lighthttpd page

### ISSUE THREAD

**Issue by VennGrayDog** [pi-hole/docker-pi-hole#1323]
### Versions

 Pi-hole version is v5.15.5 (Latest: v5.15.5)
  AdminLTE version is v5.18.4 (Latest: v5.18.4)
  FTL version is v5.21 (Latest: v5.21)
  Container tag is: 2023.02.1

### Platform

- OS and version:  Ubuntu 22.04

- Platform:  Docker

### Expected behavior

~~Landing page of PiHole shows a page that asks if I want to go to admin page.~~
http://[IPaddress:port] should show me an error page according to https://pi-hole.net/blog/2023/01/15/pi-hole-ftl-v5-20-1-web-v5-18-1-and-core-v5-15-released/ (thanks rdwebdesign)

### Actual behavior / bug

Landing page is default Lighttpd page

### Steps to reproduce

1. Go to http://IP:port
4. See wrong landing page

[✓] Your debug token is: https://tricorder.pi-hole.net/wim5hft4rq

### Screenshots

![image](https://user-images.githubusercontent.com/483837/219097188-3d2ffa28-55bb-44e3-9049-a6390c758754.png)

**Comment by VennGrayDog** [comment]
![image](https://user-images.githubusercontent.com/483837/219146419-af851b6f-e5bd-46f7-8b2e-cf72e0a9b77b.png)

**Comment by dschaper** [comment]
Oh, okay. So having the page displayed instead of a 403 didn't cause any issues, you are just reporting that the release notes don't match up to what you see? 

In that case, thank you for the notification.

**Comment by VennGrayDog** [comment]
And in my opinion displaying default Lighttpd is wrong.
The base url for Pi-Hole "service" is `http://[ip:port]'.
Any api call on the base url should either return valid result or an error. I don't consider "default page of lighttpd" as valid result.
Returning some random web page for the base url of api is dangerous.
What if lighttpd changes their default page in the future in the way that will allow unlimited access to server?

**Comment by dschaper** [comment]
Then all the default installs of `lighttpd` across all the world will suddenly be exposed. But that can't actually happen. 

The default page of lighttpd has been the standard everywhere for just about as long as `lighttpd` has been around. Apache does the same. 

API's aren't involved anywhere, there's nothing listening for API calls. Rest assured that all is well with the world (at least Pi-hole) with the current setup. Thanks for the comments and the notification about your concerns.

**Comment by VennGrayDog** [comment]
I know no other software that leaves default http page in the final release. 
The page literary says - you should replace me as soon as possible.
I will then let you folks to decide what is the best scenario here.
Thank you for you time and thank you for the great product.

**Comment by PromoFaux** [comment]
Thanks for the reminder, I kept meaning to delete it when I first saw it - life gets in the way sometimes (and it was doing no real harm).

Tagged a new image of `2023.02.2` which removes this file by default.

Worth noting that if you are using the docker image - you should also watch the releases on this repo, as sometimes there are configurations in this image that slightly differ from the bare metal installation.

For example in [2023.01](https://github.com/pi-hole/docker-pi-hole/releases/tag/2023.01) I added in a config that will auto redirect `http://${FTLCONF_LOCAL_IPV4}` or `http://${VIRTUAL_HOST}` to `/admin`. We can do that in this image because it is _very_ unlikely that someone is hosting another webpage in the `/var/www/html` directory of this container.

On bare metal we have to be careful not to overwrite people's configs

**Comment by VennGrayDog** [comment]
Thank you.
