### ISSUE TITLE
Missing logrotate package

### ISSUE THREAD

**Issue by middleagedman** [pi-hole/docker-pi-hole#153]
Maybe it's just me, but I realized that /usr/sbin/logrotate didn't get installed with the alpine build, so the system wasn't rotating logs.  Might need to add that in the install.sh.  Also I didn't have an /etc/pihole/logrotate file from upstream..but that may be due to upgrade after upgrade.  Don't know if that needs to be specifically referred to, since it is called from the "installPihole()" function as "installLogrotate()"

Ref:
https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh
https://github.com/pi-hole/pi-hole/blob/master/advanced/logrotate

**Comment by diginc** [comment]
as the image maintainer I recommend just using docker log rotation settings but I feel like a few of the processes are not compatible with that.  To have docker log rotation work pretty much all output has to go to the foreground process/stdout instead of to a file...pretty sure some stuff is still writing to files which means it may grow larger than the docker root partition can take.

Since I'm using s6-overlay the container should probably not use logrotate but instead http://www.skarnet.org/software/s6/s6-log.html

**Comment by henrik-farre** [comment]
Hi

I know this is a old issue, but still relevant.

It looks like /var/log/pihole-FTL.log is not rotated because of the missing logrotate package.

The flow looks like:
* /etc/cron.d/pihole calls `pihole flush once quiet` at 00:00 
* pihole flush calls `/opt/pihole/piholeLogFlush.sh`
* piholeLogFlush.sh checks if logrotate command exists, and runs it with the config in /etc/pihole/logrotate which is the only place which contains /var/log/pihole-FTL.log

A quick fix would be to include the logrotate package, and don't configure it as it is called explicit in piholeLogFlush.sh

**Comment by edgd1er** [comment]
Well, lighttpd is defined to write logs to /var/log/lighttpd/{error,access}.log. So it will increase the image size quite quickly. 

What i think would be a bad idea, is to redirect lighttpd outputs to stdout/stderr and mix both s6 and lighttpd messages.

So I tried today to use s6-log (s6 way to rotate logs). I can't say why but I had a hard time to understand the s6 documentation. I reused alpine-nginx idea to output lighttpd logs to 2 fifos and then use two services to have s6-logs to output to files. s6-logs handles file size limits and backups. Actual steps are:
* use fix-attrd.d to create files and dirs.
* create fifos in cont-init (stage-1)
* define new (log) services: access_log-service run, error_log service run 
* manually ovewrite lighhtpd conf (I failed to use external.conf to define server.errorlog and accesslog.filename , lighttpd include_shell is a mystery )

 Create a new image with all that. I'm not sure if this is operating as expected, I'll give it a try the next days. Nevertheless, a simple logrotate with the cron daemon embedded would have been simpler (for me), but add a new tool to the image.

If anyone is interesting in testing, improving this, i will attach the files. If anyone wish to comment the solution, he/she is welcome.

**Comment by logopk** [comment]
Any update on this?

**Comment by middleagedman** [comment]
Comment to keep this open

**Comment by PromoFaux** [comment]
> If anyone is interesting in testing, improving this, i will attach the files.

Did this work? Pull requests welcome.
