### ISSUE TITLE
'Website Blocked' page reports incorrect domain

### ISSUE THREAD

**Issue by Tatsh** [pi-hole/docker-pi-hole#156]
Instead of using the domain of the site blocked, it says *dockerpi.hole*.

I am running like so in a shell script:

```bash
docker run \
    -p 53:53/tcp \
    -p 53:53/udp \
    -p 8100:80 \
    --cap-add=NET_ADMIN \
    -e ServerIP="$IP" \
    -e WEBPASSWORD='somepass' \
    -e DNS1=192.168.1.1 \
    --restart=always \
    --name pihole \
    -v '/home/tatsh/dev/pihole-config/:/etc/pihole/' \
    -v '/home/tatsh/dev/pihole-dnsmasq.d/:/etc/dnsmasq.d' \
    -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
    -d \
    diginc/pi-hole
```

My configuration is nearly default except for a `blacklist.txt` file.

**Comment by Tatsh** [comment]
In the code `/var/www/html/pihole/index.php`, the line is: `$serverName = escapeshellcmd($_SERVER['SERVER_NAME']);` so it seems like it is taking this information from nginx, and nginx is passing the wrong value to PHP-FPM. Maybe this is because of the explicit `server_name` value set to *dockerpi.hole*. Still experimenting.

**Comment by 1activegeek** [comment]
I'm running into this issue as well. I was hoping the VIRTUAL_HOST variable would set this properly, but it doesn't seem to be doing the trick. I'm hoping someone can help here, because I want to be able to use this as an easy way for the significant other and I to easily add sites when needed. Right now, it's a complicated explanation of how to login to the pihole and complete the task. Hitting a block page, putting in the password, and being on the way would make it much easier.

**Comment by 1activegeek** [comment]
So it would still be good to get a resolution to this, but as an alternate work around - use the debian tagged version of the container. It seems that one is running as intended, and is properly grabbing the URL and allowing for use of the whitelist function.

**Comment by Lyrex** [comment]
I played a bit with the variables and found the following working for me (using the default alpine linux container):  
Use `$serverName = escapeshellcmd($_SERVER['HTTP_HOST']);` instead of the default `$serverName = escapeshellcmd($_SERVER['SERVER_NAME']);`

This should work since most proxies (including jwilder in it's default config [[1]](https://github.com/jwilder/nginx-proxy#replacing-default-proxy-settings)) forward the `Host` header to the destination server.

**Comment by 1activegeek** [comment]
@Lyrex is it possible you can make an edit and put in a pull request to rectify it? If this is working, it would be helpful so that the container can actually be changed. Otherwise manually editing the data in the container, becomes a manual effort needing to be done every time the container is created or if it's altered, needs to be done again.

**Comment by diginc** [comment]
Are the new images looking better for everyone?

**Comment by 1activegeek** [comment]
Hmm, hadn't seen there was an update. I'll see about testing it out when I have a chance. I had switched to the full image temporarily as it was working completely. I'll try the Alpine image and let you know.

**Comment by 1activegeek** [comment]
Just tested out running a fresh container, but doesn't seem to be doing the trick for me. Hitting doubleclick.com for example is still showing dockerpi.hole as the domain blocked and when attempting to whitelist, still showing as the domain blocked. 
![screen shot 2017-09-19 at 12 07 51 pm](https://user-images.githubusercontent.com/6810720/30602644-35bc6c38-9d33-11e7-8596-d9a7136b455d.png)

**Comment by Lyrex** [comment]
@1activegeek Could you maybe try to change the server_name in the nginx configuration file from `dockerpi.hole` to `_`?  
I forgot that not everyone is running the docker container behind a proxy. I will try to figure that out too if I got some spare time the next few days.

**Comment by 1activegeek** [comment]
@Lyrex - I'm not sure I understand - are you asking to modify the config inside the container itself? And would you be asking to modify this config to insert my hostname/alias/ip for the `_` you indicated?  Or literally inserting `_` to replace `docker.hole`?

**Comment by WaLLy3K** [comment]
The latest version of the Block Page (which can be checked out by running `pihole checkout core development`, and reverting with `pihole checkout core master`) uses `$_SERVER['HTTP_HOST']` instead of `$_SERVER['SERVER_NAME']` which as I understand, *should* resolve this issue.

If anyone could confirm that the issue still persists on the `development` branch, it would be massively appreciated :green_heart:

**Comment by FedoraTipper** [comment]
Just created the docker, problem still persists. Same settings as OP.

**Comment by WaLLy3K** [comment]
@FedoraTipper, could you please confirm if you were using Pi-hole's `development` branch when you posted that?

**Comment by Lyrex** [comment]
For the people trying and having problems: Are you using the docker-container standalone or in combination with a proxy (like jwilder-nginx or sth)?
I tried the new image with a nginx as reverse-proxy without any problems.

**Comment by diginc** [comment]
That would explain why I've never been able to reproduce this problem.  I am using jwilder reverse proxy by default since it makes running multiple web service containers so much easier.

**Comment by Lyrex** [comment]
I guess that's at least part of the problem. jwilder forwards the requested host header to the backend, which is dockerpi. Using `HTTP_HOST` in the config is then no problem.
An idea for fixing the problem if you can reproduce it: Change the `server_name` in the nginx.conf from `docker.pi` to `_` which is a generic catch-all hostname.
I did not have time to verify if that works but it's my best guess.

**Comment by diginc** [comment]
I'm game to `server_name` to `_` wild / default host name and put that on the dev image tags to see if it helps.  

Now that I understand the problem a more I may be able to reproduce as a py.test, writing a good test will help prevent future regressions and keep feature parity across debian/alpine.

**Comment by diginc** [comment]
I went ahead and pushed it straight to [dev branch here](https://github.com/diginc/docker-pi-hole/commit/825248fb864b3aa95969fbf6ce0b760d454277b3)

x86 diginc/pi-hole:alpine_dev has finished auto building if anyone who has had the issue could test please: https://store.docker.com/community/images/diginc/pi-hole/tags

**Comment by FedoraTipper** [comment]
Just tested alpine_dev. The problem still persists.

My settings:
docker create \
--name pihole \
-p 53:53/tcp -p 53:53/udp \
-p 85:80  \
-v /opt/pihole/:/etc/pihole/ 
-v /opt/pihole/dnsmasq.d/:/etc/dnsmasq.d/ 
-e ServerIP=192.168.1.20 \
--restart=always \
-e WEBPASSWORD="password"  \
diginc/pi-hole:alpine_dev

**Comment by jacobsalmela** [comment]
Is this still an issue?

**Comment by Tatsh** [comment]
I am using the Debian version of the image. I am not affected by this anymore. It's not a big deal to run the Debian version instead of Alpine. If Alpine is buggy I'd suggest not supporting it.

**Comment by alebupal** [comment]
Hello, any solution for this?
I am using synology and the blocking page looks this message:
`[ERROR]: Unable to parse results from queryads.php: Unhandled error message (Invalid domain!)`

**Comment by Tatsh** [comment]
See [NXDOMAIN And Null Blocking With FTLDNS](https://pi-hole.net/2018/05/18/nxdomain-and-null-blocking-with-ftldns/)

**Comment by naturalethic** [comment]
Adding ```/admin``` to the url worked for me.
