### ISSUE TITLE
setup_lighttpd_bind needed for IPv6

### ISSUE THREAD

**Issue by 5andr0** [pi-hole/docker-pi-hole#163]
include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port
This line generates $SERVER["socket"] == "[::]:$PORT" { }

[::] should be replaced with the Ipv6 from the ServerIPv6 variable, otherwise it's binding to all ipv6 adresses.

**Comment by diginc** [comment]
Can you provide a little more about why binding to all interfaces is an issue for you?  Do you use net=host mode and want to limit the available interfaces or do you have more than IPv6 interface inside a net=bridged container?

**Comment by diginc** [comment]
You could always volume mount a modified use-ipv6.pl off your docker host into the container to modify it too.

**Comment by diginc** [comment]
I think it's safe to assume this is being requested for --net=host reasons.  Adding it wouldn't be too tough in [setup_lighttpd_bind](https://github.com/pi-hole/docker-pi-hole/blob/master/bash_functions.sh#L178).  Since there is only one request for this I'm ranking this request's priority below some of the other issues.
