### ISSUE TITLE
Docker container renames my MacBook Pro's hostname

### ISSUE THREAD

**Issue by ksylvan** [pi-hole/docker-pi-hole#261]
Running the latest Docker (18.03) on my MacBook Pro.

I ran the container like the example:
```
docker run -d \
    --name pihole \
    -p 53:53/tcp -p 53:53/udp -p 80:80 \
    -v "${DOCKER_CONFIGS}/pihole/:/etc/pihole/" \
    -v "${DOCKER_CONFIGS}/dnsmasq.d/:/etc/dnsmasq.d/" \
    -e ServerIP="${IP}" \
    -e ServerIPv6="${IPv6}" \
    --restart=unless-stopped \
    diginc/pi-hole:latest
```

After a while, `hostname` on the Mac reports the long hexadecimal random name of the container host (e.g. `b39a2df6aca0`)

- [ ] Request for a new or modified feature
- [X] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

Even when setting the hostname back via `sudo hostname MyMacName`, after a while, the `hostname` command once again reports `b39a2df6aca0`

## Expected Behavior

The container should not cause the `hostname` of its host machine to change.

## Actual Behavior

The hostname of the Mac laptop is mysteriously changed to the name of the container.

## Possible Fix

Not sure what the underlying reason for this bug is, but I managed to work around it by adding
the following flags to the `docker run` invocation:

`-h $(scutil --get LocalHostName)`

## Steps to Reproduce and debugging done

1. Run the docker image.
2. Wait.
3. Execute `hostname` on the Mac host.
4. Observe the hostname has changed to some random hexadecimal container name.

## Debug steps I have tried

- [X] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [X] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [X] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 
* Docker Host Operating System and OS Version: Mac OS 10.13.1
* Docker Version: 18.03
* Hardware architecture: X86_64

**Comment by diginc** [comment]
Have you checked the docker for mac github issues for an upstream bug that matches this?

Sounds like the container's hostname is leaking outside docker onto your host mac.  Yikes.

**Comment by nxadm** [comment]
Docker for Mac uses an hypervisor, so it's less likely to "leak" than on native Linux. The workaround is not really a fix as it counts on the leaking to set your machine's hostname. Wow.

It looks to me that you're receiving your hostname through dhcp: https://superuser.com/questions/49891/how-can-i-stop-mac-os-x-overriding-my-hostname-when-i-receive-a-dhcp-request-on.

I don't think it's a bug of this container release.

**Comment by diginc** [comment]
I can't really reproduce without a mac but this sounds like a mac specific hostname behavior so I've labeled it an external bug.  Based off your ports, it's safe to assume you were not using DHCP hosted by pi-hole which I initially thought would be required for what nxadmin described to happen but...This is a bit of a leap but perhaps your router's DHCP defers hostname lookups+assignment to pi-hole and the behavior nxadm linked to applies and is confusing pi-hole's hostname with your desktop's real hostname because of the shared IP address.

The workaround of setting your desired hostname makes sense. 



Leaving this issue open for visibility for other mac users.  The readme is bloated enough as is so this is probably more visible than a note buried in the readme at this point.

**Comment by nxadm** [comment]
@ksylvan, to see if it's a Docker bug and not one caused by this image, run this and leave it open for some time (check if the hostname of your computer changes):

```
docker run -ti --rm alpine
```

If it does, we know the bug is not related to this pihole image. If it doesn't, you need to check if pihole is running an DHCP service (should be off by default). You expose port 53/udp, so it's available to all the computers in your subnet, including the hosting Mac. You can't have 2 DHCP servers on the same subnet without weird problems (of advanced configuration). In this case, it would be a configuration error.

**Comment by diginc** [comment]
Good idea @nxadm - @ksylvan could also try another docker container DNS service in place of pi-hole (make sure you take pi-hole down and up this container in it's place)

`docker run -p 53:53/tcp -p 53:53/udp --cap-add=NET_ADMIN -h DnsMasqNotPihole andyshinn/dnsmasq`

If my theory is correct it's any Router -> Docker container while the mac host and docker host share the same IP from the perspective of the router (DHCP) because of NAT then his mac should get the `DnsMasqNotPihole` hostname.

**Comment by ksylvan** [comment]
I just ran into this same issue with the latest Docker CE on the Mac, and the latest image.

```
Docker version 18.09.0, build 4d60db4

REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
pihole/pihole       latest              387a0fecc77c        2 weeks ago         296MB
```

Neither suggestion above seemed to reproduce this issue. I do think that the image at some point registers its name via DHCP and that sets the hostname on the Mac, due to DHCP and NAT, as @diginc suspects above.
