### ISSUE TITLE
Environment vars forcing use changes to reset

### ISSUE THREAD

**Issue by aptalca** [pi-hole/docker-pi-hole#283]
This is a... 

- [x] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

Passing ServerIP and such will cause this container to re-set up pi-hole from scratch, resetting any changes made in the webgui even though there is an existing setupVars.conf (which gets completely overwritten.
## Expected Behavior

I would expect that when there is an existing setupVars.conf, the values should be pulled from that, and only the new environment variables should append the existing values.
## Actual Behavior

Even if I only pass the ServerIP variable, it resets the DNS settings to defaults as well.
## Possible Fix

The start.sh (I believe) can check the values in setup.Vars.conf and append those to the environment variables passed. For instance, if the DNS was modified to 9.9.9.9, but the user creates a new image with just the ServerIP set to X.X.X.X, start.sh should run the setup with DNS set to 9.9.9.9 rather than the default 8.8.8.8.
## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1. Create and run container with ServerIP set (persistent volumes)
2. Change the DNS to 9.9.9.9 in web gui
3. Recreate container with the same variables

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [x] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

## Context and extra information

Currently, my only option is to pass the ServerIP variables only when initially creating the container, and then remove them. But I know if I ever have to change those IPs, other settings will reset back to defaults.
## Your Environment 

* Docker Host Operating System and OS Version:
* Docker Version:
* Hardware architecture:

**Comment by diginc** [comment]
It'd be easy to add a SKIP_SETUPVARS_DOCKER_SETUP or some such environment var that would do as the name implies to allow for a container to only use a pre-existing volume's setupvars config.

I do have some minor discomfort with allowing such behavior from an automation first, ephemeral service advocate perspective, mainly because it enables [configuration drift](https://dzone.com/articles/configuration-drift).  That aside, I agree this sounds valuable for power users.

It's easy enough to make it optional and advertise it as recommended in only some situations such as where a user wants to re-use a long-lived configuration volume or hand modify setupVars for other pi-hole customization reasons I may not have though to allow for in start.sh

**Comment by efficiosoft** [comment]
Ah, I see that only the things supported by start.sh are overwritten in setupVars... Then I really hope you'll never support DNS_BOGUS_PRIV etc. to be passed as environment variable, because then my manual changes will suddenly be overwritten.

Would still be very useful to disable the settings manipulation unless no setupVars is present (e.g. on first start). That would make the whole thing more straightforward because you don't have to guess which settings you are allowed to change in web interface and which will be overwritten on next restart anyway. It's not intuitive to find things like bogus priv surviving a restart, but conditional forwarding or the upstream dns servers not.

**Comment by GieltjE** [comment]
Even for newbies this would be a welcome change, if properly documented everyone should just be able to use the webgui for almost all configuration needs without havig to fear them being lost because they forgot to also update their update script (or just blatantly copy it from the docker page).

**Comment by synth3tk** [comment]
This is a pretty confusing behavior for a new user to the image. Any other image I use that allows persistence, does not completely overwrite the file on start. I'll see if I can make a PR to address it the way other images do.

**Comment by PromoFaux** [comment]
Closed in place of the pinned #720
