### ISSUE TITLE
Recommended docker run `ip route` fails on iproute2 version 4.X

### ISSUE THREAD

**Issue by diginc** [pi-hole/docker-pi-hole#312]
per [this comment in #83](https://github.com/pi-hole/docker-pi-hole/pull/83#discussion_r209324820) by @igalic

```
8.8.8.8 via 192.168.0.1 dev wlp4s0 src 192.168.0.227 uid 1000 
    cache 
```
> my iproute2 version is 4.15.0-2ubuntu1

```
echo "8.8.8.8 via 192.168.0.1 dev wlp4s0 src 192.168.0.227 uid 1000 " | awk '{ print $NF; exit }'
1000
```

Perhaps this would be a workable fix?

```
echo "8.8.8.8 via 192.168.0.1 dev wlp4s0 src 192.168.0.227 uid 1000 " | sed 's/ uid.*//g' | awk '{ print $NF; exit }'
192.168.0.227
```

**Comment by maraaaa** [comment]
How about:

```
ip -o route get to 8.8.8.8 | sed -rn 's/.*src (([0-9]{1,3}\.){3}[0-9]{1,3}).*/\1/p'
```
`.*` - match everything
`.*src` - match every thing up to src
`[0-9]{1,3}` - match a string of digits 0-9 that is 1-3 chars long. (e.g.: 0-999)
`([0-9]{1,3}\.)` - match a group of 1-3 digits, 0-999 and a period.
`{3}` - repeat the `0-999.` match three times.
`s/match (group)/\1/` - is a search and replace, we're saying replace STDOUT with our match.

This is safer as we're looking for a pattern that matches an IP instead of looking at the last column and hoping it's an IP address.  The IP of our machine will always follow the `src` string in the `ip route` command.

If you have access to Perl, I think this is a bit easier to understand:

```
ip -o route get to 1.1.1.1 | perl -ne 'print $1 if /src ((\d{1,3}\.){3}\d{1,3})/'
```

But I'm not sure if current OSX comes with Perl... so the sed version might be more universal.

**Comment by tedder** [comment]
Here after seeing that an upgrade to ubuntu 18.04 killed this startup script. I'm just hardcoding my IP for now.
