### ISSUE TITLE
Pi-hole v4.0 - please add possibility to choose blocking mode on container creation

### ISSUE THREAD

**Issue by Haxy89** [pi-hole/docker-pi-hole#318]
According to [Blocking mode - Pi-hole documentation](https://docs.pi-hole.net/ftldns/blockingmode/) there is possiblity to choose blocking mode.

How to start a container to use: `Pi-hole's unspecified IP blocking (default)`?
Also according to documentation it should be posibility to disable a web server while using this blocking mode: `No need to run a webserver on your Pi-hole (reduces complexity when running other web services on the same machine)`.

Container starting command:

`sudo docker run -d -p 53:53/tcp -p 53:53/udp -p 80:80 --name Pihole --restart=unless-stopped -v /home/pi/pihole/data/:/etc/pihole/ -v /home/pi/pihole/dns/:/etc/dnsmasq.d/ -e DNS1=1.1.1.1 -e DNS2=1.0.0.1 -e ServerIP=192.168.0.20 -e TZ=Europe/Warsaw -e WEBPASSWORD=pass -e IPv6=False pihole/pihole:v4.0_armhf`

`/etc/pihole/pihole-FTL.conf` is empty but default should contains `BLOCKINGMODE=NULL`
`/etc/pihole/setupVars.conf`  in default blocking mode should contains web servers disabled but contains:

```
DNSMASQ_LISTENING=single
DNS_FQDN_REQUIRED=false
DNS_BOGUS_PRIV=false
DNSSEC=false
CONDITIONAL_FORWARDING=true
CONDITIONAL_FORWARDING_IP=192.168.0.1
CONDITIONAL_FORWARDING_DOMAIN=home
CONDITIONAL_FORWARDING_REVERSE=0.168.192.in-addr.arpa
PIHOLE_DNS_1=1.1.1.1
PIHOLE_DNS_2=1.0.0.1
QUERY_LOGGING=true
INSTALL_WEB_SERVER=true
INSTALL_WEB_INTERFACE=true
LIGHTTPD_ENABLED=
IPV4_ADDRESS=192.168.0.20
IPV6_ADDRESS=
WEBPASSWORD=01381543e25d0e488db886f5376543e7f2530042617381c59f003796d71d7f99
PIHOLE_INTERFACE=eth0
```

I think these 3 options should be setting to false in default blocking mode:
```
INSTALL_WEB_SERVER
INSTALL_WEB_INTERFACE
LIGHTTPD_ENABLED
```
or only `LIGHTTPD_ENABLED`, if `WEB_SERVER` and `WEB_INTERFACE` is for Pi-hole user interface.

Thanks :)

**Comment by christian-ek** [comment]
Is it possible for me to select a blocking mode when running in docker now?

**Comment by christian-ek** [comment]
Yes/No?

**Comment by diginc** [comment]
Not yet on initial startup.

Down the road, I'd like to support arbitrary `PH_VARIABLES`, in this case PH_BLOCKINGMODE, that magically get passed to setupVars.conf (as regular BLOCKINGMODE) with some dynamic environment variable parsing + file injection code.  There are some ENVs that will still require some custom code to support docker by running more than just passing them into setupVars so that'll need to be handled more elegantly too, while not stepping on the generic PH_ENV injection code's toes.

The reason for this is we should be reducing the complexity of this project's bash functions and continuing to better support docker natively in the upstream docker project rather than mirroring every variable of the upstream application and/or having to re-write implementation of anything from Pi-hole. This docker image is already heavily based on the principle of re-using of the upstream project's code but the environment/configuration is one area that the majority of custom docker code was created for, but it could be simpler for sure.

My time has been occupied on other improvements for CI/CD/5.0 beta however I would love to get this into the 5.0 release if time allows.

**Comment by Freekers** [comment]
Please re-open this issue so that we don't lose focus on this. Thanks :)

**Comment by nicbou** [comment]
Closed without a fix, a solution or a comment? How is this issue resolved? @Haxy89, can you reopen it?

**Comment by gwtaylor** [comment]
> So in other words, after initial setup, I should be able to change the blockingmode by editing `/etc/pihole/pihole-FTL.conf` [as stated in the documentation?](https://docs.pi-hole.net/ftldns/blockingmode/)
> 
> I did so, but the container does not adhere to it, but I'm not sure why. I verified that the blockingmode is still set to NULL (default) by doing an `nslookup` for a domain on the blocklist. It should return the IP address of the Pi-hole if the blockingpage is enabled. However, it does not. Instead it replies with IP 0.0.0.0, which corresponds to blockingmode NULL and thus the blockpage will never show up.
> 
> Thank you.

@Freekers I was able to get working what you described above. I am using `docker-compose` with a `docker-compose.yml` that doesn't depart too much from the default in the [Quick Start](https://github.com/pi-hole/docker-pi-hole/#quick-start). This makes my local `./etc-pihole` available to the container in `/etc/pihole`. With the container running, I edited (with sudo) the blank `./etc-pihole/pihole-FTL` to add one line: `BLOCKINGMODE=NODATA`. Then I restarted the container with `docker-compose restart`.

After the container restarted, I opened up a bash term with `docker exec -it pihole bash` and took a look at the pihole-FTL logs: `tail -n 100 /var/log/pihole-FTL.log`. I can see in the log file from FTL starting up: `BLOCKINGMODE: Using NODATA for blocked domains`.

Running your test:
```bash
nslookup mobile.launchdarkly.com
Server:		192.168.1.118
Address:	192.168.1.118#53

Non-authoritative answer:
*** Can't find mobile.launchdarkly.com: No answer
```
This solved my issues with slow Chrome on a M1 Mac running Big Sur as described in https://github.com/pi-hole/pi-hole/issues/4107.

**Comment by alpe12** [comment]
Here it always return to 0.0.0.0.
Can't use anything else...
