### ISSUE TITLE
Flush logs does not work from admin panel

### ISSUE THREAD

**Issue by hansmbakker** [pi-hole/docker-pi-hole#341]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
I have pi-hole v4.0 in docker on a Raspberry Pi ([Hypriot](https://blog.hypriot.com/getting-started-with-docker-on-your-arm-device/)).

Pi-hole works but the flush logs button in the admin panel (settings page) does not work.

## Expected Behavior
Logs are removed and stats on the dashboard are reset

## Actual Behavior
Query logs are not removed and stats on the dashboard are still the same

## Your Environment 

* Docker Host Operating System and OS Version: [Hypriot Version 1.9.0](https://blog.hypriot.com/getting-started-with-docker-on-your-arm-device/); kernel: 4.14.34-hypriotos-v7+
* Docker Version: 18.06.1-ce
* Hardware architecture: ARMv7

**Comment by diginc** [comment]
Thanks for the report.

Mine did the same thing that you described.  I then disabled Pi-hole and re-enabled it, at which point the dashboard updated with no stats.

Looks like the web interface just runs `pihole -f` behind the scenes and that behaves similarly from the command line: the dashboard still shows the previous stats until you force restart.  I don't think the restart should be necessary since I don't see a restart in the [piholeLogFlush.sh](https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/piholeLogFlush.sh) source code at all.  I'll do some more checking.

**Comment by diginc** [comment]
@Mcat12 reported this is fixed on the development branch of https://github.com/pi-hole/pi-hole which I do not have an image of currently so there should be a fix down the road.

It's in my backlog to create a bleeding edge development container too.

**Comment by diginc** [comment]
This maybe fixed in the newest version.

**Comment by mr-bolle** [comment]
@diginc i flush the logs over the Admin Panel with follow Pi-Hole Versions successfull

Pi-hole Version v4.2 & v4.2.1
Web Interface Version v4.2 
FTL Version v4.2 

![04-02-_2019_08-57-50](https://user-images.githubusercontent.com/22414212/52196561-939aaa80-285c-11e9-91ac-8eba8fc81da8.jpg)

**Comment by diginc** [comment]
Thanks for confirming @mr-bolle
