### ISSUE TITLE
Error while trying to run the container

### ISSUE THREAD

**Issue by TylerWolfDev** [pi-hole/docker-pi-hole#405]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
I am running the below code
`docker run pihole/pihole -e ServerIP=(myserveriphere)`

I am getting the error below:

ERROR: To function correctly you must pass an environment variables of 'ServerIP' into the docker container with the IP of your docker host from which you are passing web (80) and dns (53) ports from

## Expected Behavior
Pi-hole should run.

## Actual Behavior
Error

## Your Environment 

* Docker Host Operating System and OS Version: Windows 10 Enterprise
* Docker Version:
* Hardware architecture:

**Comment by TylerWolfDev** [comment]
> See https://github.com/pi-hole/docker-pi-hole/blob/master/docker_run.sh for details concerning the required parameters.

I am still confused on where I would do that. I cannot find a folder to make changes on windows.

**Comment by TylerWolfDev** [comment]
@DL6ER How do I set the variables it is asking for.

**Comment by TylerWolfDev** [comment]
I have tried
`docker run pihole/pihole -e ServerIP=96.234.78.7 -p 80:80``-p 53:53/tcp -p 53:53/udp`
No luck same error

**Comment by DL6ER** [comment]
My understanding is that you should download the file https://github.com/pi-hole/docker-pi-hole/blob/master/docker_run.sh and modify it as you may need it. Instead of running any bulky `docker run ...` command directly, you should use the script which does the job for you.

**Comment by dschaper** [comment]
Everything after the name of the image is passed into the image as extra data. You need to put the image as the last item in your command line.

`docker run -e ServerIP=96.234.78.7 -p 80:80 -p 53:53/tcp -p 53:53/udp pihole/pihole`

**Comment by TylerWolfDev** [comment]
> docker run -e ServerIP=96.234.78.7 -p 80:80 -p 53:53/tcp -p 53:53/udp pihole/pihole

@dschaper I am now getting the following
`Stopping pihole-FTL
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]`
Is this normal, if so what should I do next?

**Comment by dschaper** [comment]
What tag are you using of the pihole/pihole image?

**Comment by TylerWolfDev** [comment]
> What tag are you using of the pihole/pihole image?

What do you mean by that?

**Comment by TylerWolfDev** [comment]
I used the pull command
`docker pull pihole/pihole`

**Comment by dschaper** [comment]
My example command line is not the full command line that you would use to invoke, it was just an example of what format the command line is structured in. You're missing things like the DNS overrides and linking to the local network so that DHCP works. 

Have a read through the main README.md on the repository and note the required command line contents.

**Comment by TylerWolfDev** [comment]
> My example command line is not the full command line that you would use to invoke, it was just an example of what format the command line is structured in. You're missing things like the DNS overrides and linking to the local network so that DHCP works.
> 
> Have a read through the main README.md on the repository and note the required command line contents.

@dschaper I added the only other required content and got the following error:

`Error response from daemon: driver failed programming external connectivity on endpoint jolly_euclid (b01ef11bc6323c2e8cb9b146e6b501f7702a3e38dbff60a76e1594062e83d7af): Bind for 0.0.0.0:80 failed: port is already allocated.`

**Comment by dschaper** [comment]
That's a docker error. It appears that you have an existing container that has bound to that address. You'll need to stop any other containers that use the same port, or set the Pi-hole's external web port to something other than 80. 

The Pi-hole docker image is rather complex and has some requirements that are special because of the daemon inside. You may need to gain a little more experience with docker before being able to easily run this Pi-hole image.

**Comment by TylerWolfDev** [comment]
> That's a docker error. It appears that you have an existing container that has bound to that address. You'll need to stop any other containers that use the same port, or set the Pi-hole's external web port to something other than 80.
> 
> The Pi-hole docker image is rather complex and has some requirements that are special because of the daemon inside. You may need to gain a little more experience with docker before being able to easily run this Pi-hole image.

@dschaper I was able to fix this error and ran the following command: `docker run -e ServerIP=96.234.78.7 -p 80:80 -p 53:53/tcp -p 53:53/udp --cap-add=NET_ADMIN pihole/pihole`

It says that it worked but when I go to the below link I see ads. I cannot go to the domain [pi.hole](url)

https://pi-hole.net/pages-to-test-ad-blocking-performance/

**Comment by TylerWolfDev** [comment]
@dschaper I believe I have seen people run it on Windows docker engine before.

**Comment by TylerWolfDev** [comment]
@dschaper Do you know of another way to run Pi-hole on Windows 10 without requiring a linux vm?

**Comment by dschaper** [comment]
No, I don't. It's too tied in to the tcp/ip networking stack with linux applications to be able to take control of the Windows IP stack.

**Comment by TylerWolfDev** [comment]
@dschaper I found this video that shows it being ran on Windows but not showing how.

[https://www.youtube.com/watch?v=5y2IIxrQJz4](url)

**Comment by mr-bolle** [comment]
Hi @TylerWolfDev please try follow command.

`docker run -e ServerIP=96.234.78.7 -p 81:80 -p 53:53/tcp -p 53:53/udp -e --dns=127.0.0.1 --dns=1.1.1.1 --cap-add=NET_ADMIN pihole/pihole`

* i change the Host-Port from 80 to 81 (Port 80 is in use) "Bind for 0.0.0.0:80 failed: port is already allocated"
* since pi-hole 4.1.1 you have to set the DNS to `--dns=127.0.0.1 --dns=1.1.1.1`
* if you would use a enviroment for the ServerIP please try `-e ServerIP=${myserveriphere}`
