### ISSUE TITLE
DNS parsing is slow!

### ISSUE THREAD

**Issue by thb007** [pi-hole/docker-pi-hole#434]
This is a... 

- [ ] Request for a new or modified feature
- [ ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1.
2. 
3. 
4. 

## Debug steps I have tried

- [ ] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ ] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version:
* Docker Version:
* Hardware architecture: 

I installed dnscrypt-proxy and Unbound, and now it's very slow to open the site.

**Comment by dschaper** [comment]
#
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
