### ISSUE TITLE
DNS resolution is currently unavailable  on Docker QNAP of any docker

### ISSUE THREAD

**Issue by fradducho** [pi-hole/docker-pi-hole#455]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
I'm having problems when I reboot my container with pihole and throw the same 'DNS resolution is currently unavailable' error.

-When I created the container it briefly gave me this error but it immediately starts correctly and it works, but I realized that this happens when I reboot my container and see what happens and puts the count.

I have seen everywhere in this forum and on the web in lots of places the same problem and report saying that it is solved with "--dns = 127.0.0.1 --dns = 1.1.1.1".

I have researched more and I have seen that in /etc/resolv.conf it has 127.0.0.11

According to comments from @diginc appreciated member of this community and collaborator. it would be fixed with dns = 127.0.0.1 and 1.1.1.1 but apparently the docker or whatever is not changing my /etc/resolv.conf.

Can you help me?

Every time I want to restart my docker or for some reason I have to restart my server where it is hosted docker I have to create a new pihole container.

I repeat the error it gives me when it is starting for the first time but it is immediately solved. but if I reboot the container it does not happen again.
## Expected Behavior
automatically start DNS resolution

## Actual Behavior
It does not automatically start DNS resolution

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1.
2. 
3. 
4. 

## Debug steps I have tried

- [ ] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ ] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version:
* Docker Version:
* Hardware architecture:

**Comment by TimmThaler** [comment]
Same here.
I use PiHole on a Raspberry Pi 3B. After updating the Docker Image to "4.3.1-2" (2019/06/01) the container does not start anymore due to DNS resolution unavailable. Even if I recreate the container with an older image, I get the same error/problem.

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
stty: 'standard input': Inappropriate ioctl for device
 ::: Starting docker specific checks & setup for docker pihole/pihole
OK: Checks passed for /etc/resolv.conf DNS servers

nameserver 127.0.0.1
nameserver 1.1.1.1
Assigning random password: [xxx]
stty: 'standard input': Inappropriate ioctl for device
  [i] Existing PHP installation detected : PHP version 7.0.33-0+deb9u3

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
::: Pre existing WEBPASSWORD found
Using custom DNS servers: 1.1.1.1 & 1.0.0.1
DNSMasq binding to default interface: eth0
Added ENV to php:
			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
			"ServerIP" => "0.0.0.0",
			"VIRTUAL_HOST" => "0.0.0.0",
Using IPv4 and IPv6
::: Preexisting ad list /etc/pihole/adlists.list detected ((exiting setup_blocklists early))
[... my blocklists go here ...]
::: Testing pihole-FTL DNS: FTL started!
::: Testing lighttpd config: Syntax OK
::: All config checks passed, cleared for startup ...
 ::: Docker start setup complete
  [i] Pi-hole blocking is enabled
  [✗] DNS resolution is currently unavailable
  [✗] DNS resolution is not available
[cont-init.d] 20-start.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by TimmThaler** [comment]
After deleting my config folder / pinhole data folder and creating a new container it works again.
Still strange ...

**Comment by rodgerkeesee** [comment]
Bump.  I'm using the latest pihole image on the latest QNAP version. A fresh install of pihole on QNAP Container Station works normally on the first run and then fails to start after being shutdown once. On a fresh install, it throws the "DNS resolution is currently unavailable" error but then succeeds on the second try after timeout and then starts normally. After being shutdown once it can never start again because every time the DNS resolution fails even after the timeout.

I really just need to know if the problem is with the pihole docker image or with QNAP OS, so that 
I can get it fixed.  

The pihole log file shows that different DNS servers are used in the initial start and subsequent starts. See attached... The initial start uses L] the second start of pihole starts line 114.
line 1: first boot of pihole begins
line 24: Using custom DNS servers: 127.0.0.1
Iine 46: "DNS resolution is now available"
line 114:  second start of pihole begins  
line 134: "Docker DNS variables not used"
line 135:  "Existing DNS servers used (208.67.222.222"
line 155: DNS resolution fails 

[pihole_log.txt](https://github.com/pi-hole/docker-pi-hole/files/4021459/pihole_log.txt)

**Comment by larssb** [comment]
Try this 

1. In your docker-compose.yml file. Add this line > `- "./resolv.conf:/etc/resolv.conf:ro"` under `volumes`
1. In the folder of your docker-compose.yml file create the `resolv.conf` file
1. It's contents should be:

```
nameserver 127.0.0.1
options ndots:0
```

This works for me when Pi-hole runs in host mode. N.B. I'm also running on a QNAP.

**Comment by Ardakilic** [comment]
Thanks @larssb , your trick fixed my fresh pi-hole installation on my docker compose config. The gravity was not getting updates and was giving me "dns resolution is not available" error.
