### ISSUE TITLE
Update PHP Version (7.0 -> 7.2 or 7.3) and Debian (9.5 -> 9.9)

### ISSUE THREAD

**Issue by christianbur** [pi-hole/docker-pi-hole#474]
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
In my docker-compose.yml I use the image ["pihole/pihole:latest"](https://hub.docker.com/r/pihole/pihole/)
When I run "php --version" I get the PHP version 7.0.

```
# docker exec -it dnsrec_pihole_1 php --version
PHP 7.0.33-0+deb9u3 (cli) (built: Mar  8 2019 10:01:24) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0+deb9u3, Copyright (c) 1999-2017, by Zend Technologies

# docker exec -it dnsrec_pihole_1 cat /etc/pihole/GitHubVersions
v4.3 v4.3 v4.3.1

```
[According to the PHP website](https://www.php.net/supported-versions.php) there is no active support for version 7.0 anymore. Wouldn't it make sense to update to version 7.2 or 7.3?

I also noticed that the Debian version ([9.5](https://www.debian.org/News/2018/20180714)) is a bit outdated (1 year old), the [current version is 9.9.](https://wiki.debian.org/DebianReleases)
```
# docker exec -it dnsrec_pihole_1 cat /etc/debian_version 
9.5
```

## Possible Fix
Update PHP Version to 7.2 or 7.3
Update Debian Version to 9.9

## Your Environment 

* Docker Host Operating System and OS Version: Ubuntu 18.04.2 LTS
* Docker Version: Docker version 18.09.6, build 481bc77
* Hardware architecture: x86
* Pihole: Pi-hole Version vDev (HEAD, v4.3-0-g1d43c0a) Web Interface Version vDev (HEAD, v4.3-0-g44aff72) FTL Version v4.3.1

**Comment by diginc** [comment]
Docker repo is maybe not the best spot for this since I do not pick the version inside of the docker-pi-hole source code, it is inherited from [pi-hole/pi-hole automated install/basic-install.sh](https://github.com/pi-hole/pi-hole/blob/1d43c0a2fa36ddc993db51b1751e26cbc8123fbf/automated%20install/basic-install.sh#L288).  The version is not specified there either (it is verified to be >7 but that is it). It comes from the [php-common package](https://packages.debian.org/stretch/php-common) in the latest [debian stable](https://www.debian.org/releases/) and they seem to still use 7.0.  Looks like the package php7.2-common exists in the unofficial sury.org repo.

> I also noticed that the Debian version (9.5) is a bit outdated (1 year old), the current version is 9.9.

Whoops, yes seems I forgot to setup a crontab to auto-rebuild [our base image](https://github.com/pi-hole/docker-debian-base/blob/master/Dockerfile).  Doing that should pull in the newest debian:slim-stretch base.

**Comment by diginc** [comment]
For now I'm just going to setup a crontab hitting the docker hub webhook endpoint to re-build the debian base image for me on a weekly schedule.

I think i was initially hoping checking the box 'auto rebuild when upstream image is updated' on docker hub would take care of this.  Looking closer at that check box it says in fine print 'only works on unofficial images' so using the official base image has been preventing the use of that function.

**Comment by christianbur** [comment]
@diginc 
With the regular update of Pihole something goes wrong again. 
Pihole is still using Debian 9.11, currently 9.12 

https://hub.docker.com/r/pihole/debian-base/tags -> "latest" older than two months
https://hub.docker.com/r/pihole/pihole/tags            -> "latest" older than two months
https://hub.docker.com/_/debian?tab=tags             -> "stretch-slim" Last updated 4 days ago
https://github.com/pi-hole/docker-base-images     -> "Image Builds: failing"
