### ISSUE TITLE
docker short version tags do not follow the latest long version tag

### ISSUE THREAD

**Issue by danielhoherd** [pi-hole/docker-pi-hole#482]
This is a...

- [X] Request for a new or modified feature
- [ ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

<https://hub.docker.com/r/pihole/pihole/tags>

Short Docker tags do not follow the latest long tag. EG: pi-hole:4.3 does not reference the same image as 4.3.1-4. Instead, it references the original 4.3 release which is 6 weeks old.

Having short tags follow the latest of a longer tag is a common behavior for docker images which allows increasing specificity for required versions. (EG: postgres:9 is always whatever the latest 9.x release is.)

## Expected Behavior

Any shortened tag will point to the latest version built of any sub-version of that tag. Some theoretical examples:

- 4 points to 4.3.1, and when 4.3.2 comes out 4 will then point to 4.3.2
- 4.3 points to 4.3.1, and when 4.3.2 comes out 4.3 will point to 4.3.2
- 4.2 will never point to anything other than 4.2.*
- Future tag 5 will never point to anything other than 5.* (ie: it will never point to the latest version of 4)

## Actual Behavior

Tags always point to the same image, never updating when new versions come out.

## Possible Fix

I would reference other projects that have this behavior and have a similar build pipeline to see how they handle dynamic tag reassignment.

## Context and extra information

I have had problems in the past with upgrades breaking my config, so I was trying to avoid using :latest while still getting security and bug fixes. The only way to get security and bug fixes appears to be to use :latest.

**Comment by diginc** [comment]
`latest` tag is the only floating tag I update to point to newer versions.  Every other versioned tag is a specific version, typically matching what the upstream Pi-hole release version number is.  I recognize this is not like some of the official docker images which don't have the 2nd/3rd dot version number included in their tags and people could be confused by this.

Perhaps I should tag `pi-hole:4.3` -> `pi-hole:4.3.0` instead to avoid confusion?  

Otherwise the deploy script I use would need some updating to handle the secondary (zero dot) and tertiary (one dot) semantic version tags.  The expected behavior you cover explains the perfectly.   It would just take a bit more code and or re-running of my deploy script with more (less specific) versions.

**Comment by nathang21** [comment]
+1 would love to see some better management of tags here.

Pihole specifically reccomends not upgrading to the latest major release automatically, but I'd like to be able to pull the latest minor release via a tag, and upgrade to that automatically (which should have no breaking changes).

I plan to have a cron pull the latest images weekly and restart my container, but I guess I'll have to use latest or wait this to be addressed first.

**Comment by GeoCookie** [comment]
Still occurs today. v5.8 tag is still pointing to v5.8.0 and not v5.8.1

**Comment by PromoFaux** [comment]
> Still occurs today.

Of course it does. We've never stated that it was otherwise.

We've recently had a lot of internal discussion about this. Simply put, the versioning of the container doesn't really follow SemVer... 

There are three components in the docker container:
 - Core - currently v5.3.1
 - Web - currently v5.5.1
 - Ftl - currently v5.8.1 (Where the docker tag gets it's version number from)

There isn't really a meaningful way to translate that into a tag that has any kind of relevance to semantic versioning. What happens, now, if Core goes to 5.4? Sure, Docker could go to 5.9, but that doesn't really _mean_ anything.

We're looking into the idea of moving to `year.month[.revision]` (i.e `2021.08[.1]`), with the `year.month` potentially always being whatever the latest `year.month.revision` is. But even still, this has no real bearings on the versions of the Pi-hole components inside the container, and again - there isn't really a meaningful way to do this that follows semantic versioning in any kind of way that makes logical sense.

Personally speaking: I strongly suggest that nobody upgrades a Pi-hole docker container automatically, for the very same reason we do not include an automatic upgrade path on a bare metal install. It's just asking for trouble. Sure, a point/bugfix release _shouldn't_ have any breaking changes... but things go wrong sometimes, and you should be there to roll back/fix it. DNS is an integral part of your network, one which you should set aside time for when planning on making changes to it.

**Comment by dschaper** [comment]
We've discussed having floating tags but we don't have the capability currently to ensure that is possible.

**Comment by danielhoherd** [comment]
It sounds like a prerequisite problem to even looking at floating tags is figuring out how to version the pihole container. It's a conglomerate, and those components apparently don't have any lock-step in their versions. I've seen cases like this successfully handled in one of two ways: you version it after the main component that other things revolve around, or you create a new product version that stands aside from any version number of the components that comprise the product. I'm not sure what the best approach would be here, but it seems like one of those would work.

**Comment by PromoFaux** [comment]
Versioning changed in `:2021.09`. rationale is explained therein:

https://github.com/pi-hole/docker-pi-hole/releases/tag/2021.09

**Comment by danielhoherd** [comment]
@PromoFaux thanks for looping back on this and closing it out! great news :)

**Comment by danielhoherd** [comment]
Also in your defense your comment above mentioned that the team was just looking into what was later implemented, so it's great to see that a decision was made and that it is easy to understand.
