### ISSUE TITLE
FR: DNS-over-TLS

### ISSUE THREAD

**Issue by eku** [pi-hole/docker-pi-hole#486]
This is a... 

- [x] Request for a new or modified feature
- [ ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

Support for DNS-over-TLS in the default docker image would be great. But please with the possibility to use your own DNS server and not 1.1.1.1 because of privacy concerns.

https://docs.pi-hole.net/guides/dns-over-https/

https://github.com/getdnsapi/stubby

**Comment by heartbleeded** [comment]
Did you manage to setup dockerized pihole and DNS-over-TLS?

**Comment by Joostvanderlaan** [comment]
I found these 2 projects trying to accomplish this: 
https://github.com/eldridgea/erised
https://github.com/kquinsland/skyhole

**Comment by mcarson75** [comment]
I have modified the Pi-Hole docker image to also include unbound, which you can configure to use DNS-over-TLS with whichever servers you want:

[https://github.com/mcarson75/unbound-pihole](https://github.com/mcarson75/unbound-pihole)

Docker image mcarson75/unbound-pihole

**Comment by CumpsD** [comment]
Would be nice to have this in the `pihole/pihole` image

**Comment by pladaria** [comment]
To me this is a must because my ISP is intercepting DNS calls

**Comment by buckaroogeek** [comment]
I found a simple DNS-Over-HTTPS client written in Go along with a companion docker compose yaml file and rolled that into my existing docker compose yaml used to manage a pi-hole instance, among other services. Documented at https://github.com/buckaroogeek/unifi-pihole-doh-docker.

**Comment by jol64** [comment]
I don´t really want to hijack that issue, but I think it is pretty close to what I want.
Actually I tried to combine docker images for pihole and stubby (I used https://hub.docker.com/r/mvance/stubby, but looking at the complexity I´d opt for https://hub.docker.com/r/flexo3001/stubby). The issue I ran into is that I cannot reference the stubby container as DNS1: stubby#8053 (or #53 depending on what the container exposes) because dnsmasq expects an IP address rather than a DNS name. If you could convert the name to IP address within https://github.com/pi-hole/docker-pi-hole/blob/master/bash_functions.sh, then I assume it would be kind of trivial to get DNS-over-TLS.
Thanks, Joachim

**Comment by b13sch** [comment]
Hi, please add DoT in the default docker image! I'm interested, too! How can we push this?

**Comment by dschaper** [comment]
It's not something that will happen, sorry.

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.
