### ISSUE TITLE
Ability to change cache-size dnsmasq option

### ISSUE THREAD

**Issue by nightah** [pi-hole/docker-pi-hole#526]
This is a... 

- [X] Request for a new or modified feature
- [ ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

Currently if you attempt to modify the `cache-size` option in the dnsmasq config `01-pihole.conf` this is overwritten upon restart of the container.
Ideally we should be able to specify the `cache-size` with an environment variable that is bootstrapped into the config.

## Expected Behavior

The ability to change the `cache-size` option preferably via a environment variable.

## Actual Behavior

The `cache-size` option will always be 10000 in the docker container because of how the container initialises.

## Possible Fix

For now I have mapped a file with my modified `cache-size` to `/etc/.pihole/advanced/01-pihole.conf` in the container as this is what is utilised for initialisation.

Ideally I think this will require a modification of the `bash_functions.sh` and the default file `/etc/.pihole/advanced/01-pihole.conf` to allow us to bootstrap this setting via an environment variable.

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1. Modify `cache-size` option in `01-pihole.conf`
2. Restart pihole container
3.  Observe `cache-size` is reset to 10000 (the default)

## Debug steps I have tried

Currently I have a workaround in place.

- [X] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [X] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [X] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version: Arch Linux 5.3.7 kernel
* Docker Version: 19.03.4-ce
* Hardware architecture: amd64

**Comment by Veduco** [comment]
Version: Pi-hole v5.2.4 Web Interface v5.4 FTL v5.7

This is still a problem today on the above version due to the fact the docker container copies 01-pihole.conf on every boot, overwriting the set configuration.

Mapping 01-pihole.conf from the host as a read only file causes:
`[cont-init.d] 20-start.sh: executing... 
 ::: Starting docker specific checks & setup for docker pihole/pihole

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
install: cannot remove '/etc/dnsmasq.d/01-pihole.conf': Device or resource busy
  [i] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf...[cont-init.d] 20-start.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.`
which then fails to start, and perpetually reboots.



Leaving this file to be autogenerated based on the provided environmental variables yields:
`[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
 ::: Starting docker specific checks & setup for docker pihole/pihole

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
Converting DNS1 to PIHOLE_DNS_
Converting DNS2 to PIHOLE_DNS_
Setting DNS servers based on PIHOLE_DNS_ variable
::: Pre existing WEBPASSWORD found
DNSMasq binding to default interface: eth0
Added ENV to php:
                        "PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
                        "ServerIP" => "0.0.0.0",
                        "VIRTUAL_HOST" => "0.0.0.0",
Using IPv4 and IPv6
::: Preexisting ad list /etc/pihole/adlists.list detected ((exiting setup_blocklists early))
::: Testing pihole-FTL DNS: FTL started!
::: Testing lighttpd config: Syntax OK
::: All config checks passed, cleared for startup ...`
`  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf`

On a standard, non-docker deploy, a user is expected to modify setupVars.conf.
In a docker deploy, environmental variables are to be used, of which none exist to control the cache specifically.

The container's supported environmental variables should at least match setupVars.conf's ability.

**Comment by nightah** [comment]
@Veduco the workaround you're using won't work for exactly the reason you're seeing, if you read the workaround I posted you're actually mounting in a different file which won't conflict and cause device busy issues.

**Comment by PeterDaveHello** [comment]
I believe this one needs to stay open.

**Comment by PeterDaveHello** [comment]
Oh, looks like I followed an old issue, I believe this was resolved by #689 already, tested it and it's working!

**Comment by PromoFaux** [comment]
Indeed! Docs here for anyone else coming across this issue: https://github.com/pi-hole/docker-pi-hole#advanced-variables
