### ISSUE TITLE
monolithic cache + Pi hole 

### ISSUE THREAD

**Issue by warmach1ne** [pi-hole/docker-pi-hole#544]
Hello,

I am running a steamcache server using monolithic lancache. I would like to run pi hole as well. Monolithic uses 443, 53 and 80 for cache.

Is it possible to run both monolithic lancache-dns and pi hole in same docker container using the port 53 and 80? or is there another way I can run both services with different dockers but using one port 53 and 80?

Thank you.

**Comment by diginc** [comment]
For just 80/443 webservers there are a few reverse proxy solutions that work and can route multiple webapps to different docker containers as needed.  We have an example one for Traefik here : https://github.com/pi-hole/docker-pi-hole/blob/master/docker-compose-traefik-proxy.md

You may need to readup a little about reverse proxies / traefik since I don't want to go into a full blown tutorial here.

> Is it possible to run both monolithic lancache-dns and pi hole in same docker container 

Generally docker is more for single purpose containers that do one thing and do it well.  Spinning up each one individually and having them play nicely should be totally possible with the right docker networking setup and tools like Traefic to handle all your web traffic and route requests to whatever your'e requesting, be it Pi-hole or monolithic lancache.

Here's the elevator pitch for a docker reverse proxy like Traefik: Say you have 10 webapps that ordinarily would conflict on port 80, you give them random ports for the web interface instead of port 80, then traefik takes port 80 and routes by hostname to the appropriate random port (deteted using docker) for the other web apps' containers. 

It is a little bit magic but the example we provided should just work and then you'll need to get the lancache setup with the right configuration to also be served up by Traefik (if you choose to go that way).

I've also used and can recommend the jwilder-nginx proxy container which might be slightly easier if you're familiar with nginx already.  It adds docker random port routing magic to nginx very similarly to traefik and lets you mix in your own nginx configs as desired. [example for jwilder + pihole was the original recommendation pre-traefik](https://github.com/pi-hole/docker-pi-hole/blob/master/docker-compose-jwilder-proxy.yml).

Also see the 4th bullet of tips and tricks section or the [readme](https://github.com/pi-hole/docker-pi-hole#tips-and-tricks)

**Comment by warmach1ne** [comment]
Thank you so much. I was looking for a direction. I will read on reverse proxies/traefik also jwilder-nginx proxy container. Thanks again.
