### ISSUE TITLE
Please tag versions

### ISSUE THREAD

**Issue by apeeters** [pi-hole/docker-pi-hole#545]
Quick questions: please tag the versions released on Docker Hub in Git.

Thanks!

**Comment by NazarKosteckij** [comment]
This will be usefull: 
If you see that new version of the pi-hole avaliable and stop and pull of latest image doesnt help - follow next steps: 

- stop pi-hole docker containe `docker stop pihole`
- remove stopped container `docker rm $(docker ps -qa)`
- remove outdated docker image `docker image rm pihole/pihole`
- pull the lates image from registry `docker pull pihole/pihole:latest`
- run it as you runed it before

**Comment by dschaper** [comment]
No need to `docker image rm` anything, pulling will update to the latest if there's an update. And if you start with `docker run --rm` then the container will be removed when stopped.

But the more important thing is tagging so that you don't have to use `latest`, you can pin to what version you'd like to stay at or pull a specific version.

**Comment by diginc** [comment]
Production releases have typically been [tagged + released on githb](https://github.com/pi-hole/docker-pi-hole/releases) however it was manual before now.  This version is mirrored in the [docker hub tags ](https://hub.docker.com/r/pihole/pihole/tags)

A recent addition to our dev branch is a new CI / CD configuration that automatically pushes pre-prod / branch dockerhub builds. This continous deployment should work for tags/releases also so now the only manual step will be tag a version in github to automatically create the build in docker hub.

https://github.com/pi-hole/docker-pi-hole/pull/552
