### ISSUE TITLE
Logrotate is a must with current docker image design

### ISSUE THREAD

**Issue by chrodriguez** [pi-hole/docker-pi-hole#596]
As docker images shall run on service per container and also expose logs to stdout or stderr, but in this case the image considers using a design based on a supervisor process that manages chidl subprocess, logs need to be written to disk.

The problem is when heavy usage of all service generate logs and make runing container image to grow with logs. 
This is a.
- [x] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
Add logrotate package and configurarion for log rotation of used services, in order to minimize the size of container filesystem virtually created (See output of `docker ps -s <PIHOLE-CONTAINER>` after some days of normal or heavy usage).

## Expected Behavior
To minimize the amount of virtually created inside container used by logs

## Actual Behavior
Container image grow infinetey.  

## Possible Fix
Alternatively, an emtpyDir with sizeLimit can be  used within kubernetes to fix this problem, but when sizeLimit is reached container will be recreated.
  
## Steps to Reproduce and debugging done
e.g. your docker run command, pages to visit, CLI commands you ran
1. while true; curl -qs  CONTAINER_IP ; done
2. inspect ouputu of ,docker ps -s CONTAINER_ID>

## Context and extra information

I can see someone mentions this problem in #153 

## Your Environment 
* Kubernetes cluster using [helm pihole chart version 1.3.2](https://hub.helm.sh/charts/mojo2600/pihole)  
* Docker Host Operating System and OS Version: CentOS 7
* Docker Version: 18.06.2-ce
* Hardware architecture: x86

**Comment by edgd1er** [comment]
HI, 

I have comment in #153 the log rotation for lighttpd. I'm not sure cron produce a lot of logs... other logs are under control.
The idea is to use s6-log to handle logs as logrotate would.
lighthttpd would write to 2 fifos (access, error), two services would pick the two fifos and write logs with rotation. I need to do further test to validate that a rotation is performed :)

**Comment by edgd1er** [comment]
Hi,

It seems lighttpd cannot handle /dev/stderr since 2015. Not sure if it was corrected since, but I could not have lighttpd directly accessing to /dev/stderr stdout. My proposition is to create two fifos for lighttpd to dump its logs in them. Then have to service to redirect fifos to stderr and stdout.

In the archive you will find, the Dockerfile to build a new image in order to add needed files. I assumme a docker cp would be enough to change a running container.

[pihole.lighthttps.log2dev.zip](https://github.com/pi-hole/docker-pi-hole/files/4487255/pihole.lighthttps.log2dev.zip)

I would be nice to have this way to log by default or activable by a ENV variable.
