### ISSUE TITLE
Docker: dns-servers.conf is replaced if exists when PiHole start in the container

### ISSUE THREAD

**Issue by mikaelparkefelt** [pi-hole/docker-pi-hole#602]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

If I replace adlists.list before start of docker container. The file IS NOT replaced by the default one.
If I replace dns-servers.conf before start of docker container. The file IS NOT replaced by the default one.

**Actual behaviour:**

If I replace adlists.list before start of docker container. The file is not replaced by the default one.
If I replace dns-servers.conf before start of docker container. The file IS replaced by the default one.

**Steps to reproduce:**

1. Create a docker volume with the following files:
- adlists.list
- dns-servers.conf

2. Use the volume when starting the continer.

3. Connect with console to the container. No you will se that adlists.list i the one that we used before starting the container. dns-servers.conf is replaced with the default one and not the one that was added before start.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A

**Troubleshooting undertaken, and/or other relevant information:**

None

**Comment by thomasmerz** [comment]
I also have watched this behaviour that my dns-servers.conf is reset after each restart of my pihole container 😞   
❓ Does this really have an **impact on the upstream dns resolvers being used** if I have them already in setupVars.conf (which is not reset after each container restart)?  
❓ Or is this **only an issue in the web gui** that I can't see (and check/uncheck) them my wanted upstream resolvers?

**Comment by PromoFaux** [comment]
`dns-servers.conf` is not supposed to edited by the user. It is generated when the [installer is run](https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L1465-L1469)

Editing this file has no bearing on what actual upstream servers are used. If you want to set more than 2 custom upstreams, then you can use the  `PIHOLE_DNS_` environment variable in docker

**Comment by thomasmerz** [comment]
I'm not sure, if we are talking about the same thing 🤔  

I tried this in my `docker-compose.yaml`
```
…
    environment:
      - PIHOLE_DNS_1=208.67.222.222
      - PIHOLE_DNS_2=208.67.220.220
      - PIHOLE_DNS_3=84.200.69.80
      - PIHOLE_DNS_4=84.200.70.40
      - PIHOLE_DNS_5=9.9.9.9
      - PIHOLE_DNS_6=149.112.112.112
      - PIHOLE_DNS_7=9.9.9.11
      - PIHOLE_DNS_8=149.112.112.11
      - PIHOLE_DNS_9=1.1.1.1
      - PIHOLE_DNS_10=1.0.0.1
      - PIHOLE_DNS_11=45.90.28.39
      - PIHOLE_DNS_12=45.90.30.39
      - PIHOLE_DNS_13=94.140.14.14
      - PIHOLE_DNS_14=94.140.15.15
```
and got this after `docker-compose --no-ansi pull; docker-compose --no-ansi stop && docker-compose --no-ansi up -d`:

<img width="974" alt="image" src="https://user-images.githubusercontent.com/18568381/110333216-a080be00-8021-11eb-806d-c428498de3ee.png">

Instead of this:

<img width="975" alt="image" src="https://user-images.githubusercontent.com/18568381/110333441-df167880-8021-11eb-8fc9-db525b367b76.png">

After customizing `dns-servers.conf`:

```
dns-servers.conf
Google (ECS);8.8.8.8;8.8.4.4;2001:4860:4860:0:0:0:0:8888;2001:4860:4860:0:0:0:0:8844
OpenDNS (ECS, DNSSEC);208.67.222.222;208.67.220.220;2620:119:35::35;2620:119:53::53
Level3;4.2.2.1;4.2.2.2;;
Comodo;8.26.56.26;8.20.247.20;;
DNS.WATCH;84.200.69.80;84.200.70.40;2001:1608:10:25:0:0:1c04:b12f;2001:1608:10:25:0:0:9249:d69b
Quad9 (filtered, DNSSEC);9.9.9.9;149.112.112.112;2620:fe::fe;2620:fe::9
Quad9 (unfiltered, no DNSSEC);9.9.9.10;149.112.112.10;2620:fe::10;2620:fe::fe:10
Quad9 (filtered + ECS);9.9.9.11;149.112.112.11;2620:fe::11;2620:fe::fe:11
Cloudflare;1.1.1.1;1.0.0.1;2606:4700:4700::1111;2606:4700:4700::1001
AdGuard DNS (default);94.140.14.14;94.140.15.15;2a10:50c0::ad1:ff;2a10:50c0::ad2:ff
AdGuard DNS (family);94.140.14.15;94.140.15.16;2a10:50c0::bad1:ff;2a10:50c0::bad2:ff
NextDNS;45.90.28.39;45.90.30.39;2a07:a8c0::61:fbae;2a07:a8c1::61:fbae```
```

and after a `docker exec -it pihole pihole restartdns reload-lists`.

My `setupVars.conf` looks both fine (before or after manual editing of `dns-servers.conf`) with these 14 lines:
```
PIHOLE_DNS_1=208.67.222.222
PIHOLE_DNS_2=208.67.220.220
PIHOLE_DNS_3=84.200.69.80
PIHOLE_DNS_4=84.200.70.40
PIHOLE_DNS_5=9.9.9.9
PIHOLE_DNS_6=149.112.112.112
PIHOLE_DNS_7=9.9.9.11
PIHOLE_DNS_8=149.112.112.11
PIHOLE_DNS_9=1.1.1.1
PIHOLE_DNS_10=1.0.0.1
PIHOLE_DNS_11=94.140.14.14
PIHOLE_DNS_12=94.140.15.15
PIHOLE_DNS_13=45.90.28.39
PIHOLE_DNS_14=45.90.30.39
```

I find it really **confusing** that I can't add more DNS resolvers in the GUI and that I can't get rid of some that I don't want (to use) in the GUI, too 😕 Are they just "hidden" in the GUI and still being used?

**Comment by PromoFaux** [comment]
Please review the `README` for how to use `PIHOLE_DNS_` environment variable:

https://github.com/pi-hole/docker-pi-hole#environment-variables

As mentioned, `dns-servers.conf` does not need to be edited. It's there so that if we added/removed upstream DNS server options from the installer, we wouldn't need to remember to replicate that in the web interface.  That file only shows what is in the web interface, it has no bearing on what upstreams are actually used.

All this besides, there really is no need to set that many upstream DNS servers!
