### ISSUE TITLE
Addresses outside my local network connect to my Pi-Hole / Docker on my ASUSTOR nas.

### ISSUE THREAD

**Issue by antoinela** [pi-hole/docker-pi-hole#652]
## Details
Hello and thank you for your work.
I installed DOCKER / Pi-Hole on my ASUSTOR nas.
Pi-hole works very well. By cons I have a concern. I have external IPs that appear in NETWORK OVERVIEW and QUERY LOG.

My ASUSTOR nas is equipped with a firewall. Which normally is well adjusted. On my nose I have no external connection.

All of this worries me.

For the moment I have turned off Pi-Hole and Docker.

Thank you.

## Related Issues
 I did not find anything on the forums regarding my problem on a nas asustor.

## How to reproduce the issue 

1. Environment data
  * Operating System: **ADM (Asustor)** 
  * Hardware: Nas ASUSTOR AS-5104T
  * Docker Install Info and version: 
    - Software source: 
    - Supplimentary Software: 
  * Hardware architecture: 

![Capture d’écran 2020-07-14 à 09 52 44](https://user-images.githubusercontent.com/11404529/87511339-6ff4aa00-c675-11ea-8dcc-ef3daca89212.png)

**Comment by antoinela** [comment]
I need your help, please.

**Comment by diginc** [comment]
> On my nose I have no external connection.

How have you confirmed this?  Does the NAS firewall show connections to it only coming from your internal network?  Have you tried connecting to your IP address from an external address to confirm you're blocking external connections?  

Sorry but external access doesn't just magically get granted in the docker layer - it happens because whatever gave docker network granted external network access so you must have a larger network issue beyond docker pi-hole.
