### ISSUE TITLE
Raspberry Pi Zero - Container restarting

### ISSUE THREAD

**Issue by NxP4Code** [pi-hole/docker-pi-hole#671]
### Platform
- OS and version:  Raspbian
- Platform:  Raspberry Pi Zero

### Expected behavior

Container continuously restarting when use following command to start container

docker run -d \
    --name pihole \
    -p 53:53/tcp \
    -p 53:53/udp \
    -p 67:67/udp \
    -p 80:80 \
    -p 443:443 \
    -e PUID=1000 -e PGID=1000 \
    -e TZ=America/Chicago \
    -v /home/pi/pihole/:/etc/pihole/ \
    -v /home/pi/pihole/dnsmasq.d/:/etc/dnsmasq.d/ \
    -e 127.0.0.1 \
    -e 8.8.8.8 \
    --restart=unless-stopped \
    pihole/pihole:latest

### Actual behavior / bug

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying...
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing...
[cont-init.d] 20-start.sh: exited 267.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by rndnoise** [comment]
I'm also having this issue. When I start it with `docker run --rm -ti --entrypoint /bin/sh` to override the `ENTRYPOINT` directive, there is no output, and an exit status of 139. In fact, I can't get any programs to run as the entrypoint except `/s6-init`.

Are you using the `pihole/pihole:v5.1.2` image? I noticed [here] that there isn't an arm/v6 tag, so I'm confused why Docker even tries to fetch the image. My guess is that it's downloading and trying to run the arm/v7 image, which is not binary compatible with the Pi Zero's processor. Maybe `/s6-init` happens to be compatible with both arm v6 and v7, so that much executes but when it tries to launch a shell to run 20-start.sh, the shell cannot execute.

**Comment by rndnoise** [comment]
This appears to be a known issue: https://github.com/moby/moby/issues/41017#issuecomment-632942980. Moral of the story is you need to build your own armel image for pihole (they don't provide one). If you install a multi-arch image like pihole/pihole, you may need to specify the checksum (eg, `docker run foo/bar@sha256:nnnnn...` so that Docker will choose the correct image.

**Comment by kernitus** [comment]
I am seeing the same problem, but with the arm64 image. Thus, I don't think it's an image architecture issue, but something else :thinking:

**Comment by Idesmi** [comment]
> I am seeing the same problem, but with the arm64 image. Thus, I don't think it's an image architecture issue, but something else thinking

Did you solve it? I'm having the same issue, on the Zero.

**Comment by lightswitch05** [comment]
This isn't an answer to your question, but on a single core device like a pi zero, it might not be worth the overhead of running PiHole via docker. I'm not sure what all you are doing with it, but Pi-hole runs great outside of docker without all the added overhead. Anyways, might be worth considering for single core 1GHz devices.

**Comment by dschaper** [comment]
Will arm64 even run on a Zero?

**Comment by rndnoise** [comment]
@dschaper No, it only has a 32-bit runtime. However, I have been able to successfully build run Pi-hole on it by targeting docker buildx's "linux/arm/v6" platform. While it's not under heavy load, it performs fine for a home network with ~20 devices, also running unbound as the resolver.

Feel free to take a look at my fork of this project, https://github.com/rndnoise/docker-pihole. I've made some big changes after forking though, and I'm not sure if the documentation is still correct.

**Comment by rndnoise** [comment]
Forgot to mention, I have confirmed building only for "linux/arm/v6", and **not** v7, allows both Pi Zero W and Pi 3B+ to select a working image. I don't know if there's a benefit to compiling a v7 image, since I think it's still 32-bit... maybe it's compiled with hardware supported floating point operations?

**Comment by kernitus** [comment]
> This isn't an answer to your question, but on a single core device like a pi zero, it might not be worth the overhead of running PiHole via docker. I'm not sure what all you are doing with it, but Pi-hole runs great outside of docker without all the added overhead. Anyways, might be worth considering for single core 1GHz devices.

I wasn't actually running it on a Pi Zero, but a Pi 3 and then a 4. I had simply gotten the same error message. Unfortunately I don't remember how I got it fixed.

**Comment by Idesmi** [comment]
@rndnoise Would you be able to provide a built docker image from your repo?

**Comment by rndnoise** [comment]
@Idesmi Sorry, I don't have the interest to support other people using the build. But you're welcome to fork it and use it to build your own image. The build is done on GitHub, you only need to configure secrets named DOCKERHUB_USERNAME and DOCKERHUB_PASSWORD and push a commit to trigger the build.
