### ISSUE TITLE
Incorrect BOGUS for bevyengine.org (using Google DNS)

### ISSUE THREAD

**Issue by JohnPeel** [pi-hole/docker-pi-hole#747]
### Versions

- Pi-hole:  v5.2.2
- AdminLTE:  v5.2.2
- FTL:  v5.3.4

### Platform

This is running inside of Docker with the normal image, below are the host's information.

- Host OS and version:  Debian 10 (Raspberry Pi OS x64)

- Host Platform:  Raspberry Pi

### Expected behavior

A or AAAA lookup of bevyengine.org should returns a CNAME record to bevyengine.github.io.

### Actual behavior / bug

The dns server returns SERVFAIL with BOGUS in the logs.

I've verified that neither bevyengine.org nor github.io have DS, DNSKEY, or RRSIG records.

Google DNS also returns the records completely fine using dig from the docker container.

### Steps to reproduce

1. Go to [bevyengine.org](bevyengine.org).

## Debug Token

- URL:  https://tricorder.pi-hole.net/6fob9n83fn

### Screenshots

![image](https://user-images.githubusercontent.com/414664/103390409-4bd13c00-4ae2-11eb-9628-870d6c31f606.png)
![image](https://user-images.githubusercontent.com/414664/103390162-e29cf900-4ae0-11eb-86c4-8e6ebe2fe156.png)
![image](https://user-images.githubusercontent.com/414664/103390385-2cd2aa00-4ae2-11eb-8b47-b2dbb50cdbfc.png)

**Comment by dschaper** [comment]
As a side note, the domain is not configure correctly, and that may lead to issues. It looks like it's meant to use GitHub pages but there's a CNAME configured for it. Since it's an apex domain it needs to be configured as an A record.

https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain

**Comment by DL6ER** [comment]
Closing this as the issue lies outside of Pi-hole. This has been demonstrated by switching from Google DNS to OpenDNS so Google is returning invalid data here. I'm also getting the expected `INSECURE` result from my local `unbound` resolver through Pi-hole:

![Screenshot from 2020-12-31 12-35-35](https://user-images.githubusercontent.com/16748619/103408911-c17dec00-4b64-11eb-8127-73241f7f2a5f.png)
