### ISSUE TITLE
Web UI refusing connection after container restart (compose read timeout)

### ISSUE THREAD

**Issue by DerRockWolf** [pi-hole/docker-pi-hole#785]
### Versions

- Pi-hole:  5.2.4
- AdminLTE:  5.3.2
- FTL:  5.6

### Platform

- OS and version:  Linux alpine-pi 5.4.84-0-rpi

- Platform:  Docker 20.10.3

### Expected behavior

When restarting/rebuilding the container it should boot without any errors and everything (DNS request blocking, web UI) should work without any issues.

### Actual behavior / bug

After the container has been restarted/rebuilt the following error message is being printed
```
ERROR: for pihole  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for pihole  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```
and the web UI is refusing the connection. The blocking of DNS requests is working regardless.

### Steps to reproduce

1. `/etc/resolv.conf` should be set to the IP of the host
2. The [quick start](https://github.com/pi-hole/docker-pi-hole#quick-start) docker-compose.yml should be used
3. Execute `docker-compose up -d` and reboot the system
4. Manually restart the container
5. See error

### Additional context

- When changing the `nameserver` in `/etc/resolv.conf` on the host to either `127.0.0.1` or to any other DNS server such as `8.8.8.8` and restarting the container the error won't appear and the web UI is accessible.
- When providing the container with a DNS server (`127.0.0.1` or `8.8.8.8`) via the `docker-compose.yml` or the `--dns` flag and rebuilding the container the error is being printed but the web UI is accessible regardless of the error.

**Comment by jackm** [comment]
I too had this same problem, and after re-reading the README I saw that it was also necessary to add DNS servers to the docker-compose file as [explained in the _upgrade notices_ section](https://github.com/pi-hole/docker-pi-hole#docker-pi-hole-v411).

i.e. appending the following under the "_pihole_" docker-compose service:
```
dns:
  - 127.0.0.1
  - 1.1.1.1
```

I am not sure why the [quick start docker-compose example text](https://github.com/pi-hole/docker-pi-hole#quick-start) and the [docker-compose.yml.example](https://github.com/pi-hole/docker-pi-hole/blob/master/docker-compose.yml.example) file are missing these DNS server entries, but they appear to be necessary otherwise bringing the docker container down and then up again will fail.
